---
title: "ggplot2"
author: Xinyun Hu
date: "7/6/2020"
output:
  html_document: default
  pdf_document: default
---
Learn data visualization with `ggplot2`.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r, message = F}
#National Parks in California
ca <- read_csv("data/ca.csv") 

#Acadia National Park
acadia <- read_csv("data/acadia.csv")

#Southeast US National Parks
se <- read_csv("data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("data/mass.csv")
```
```{r}
head(ca)
```
```{r}
ggplot(data = ca) + 
  geom_point(aes(x = year, y = visitors, color = park_name)) + 
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") + 
  theme_bw() + #white background, there are alse many other themes
  theme(legend.title = element_blank())
```
```{r}
ggplot(data = se) +
    geom_point(aes(x = year, y = visitors)) +
    facet_wrap(~ state)
```
```{r}
ggplot(data = se) +
     geom_point(aes(x = year, y = visitors, color = park_name)) +
     facet_wrap(~ state, scales = "free")
```
```{r}
ggplot(data = se) + 
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), 
              width = 0.1, 
              alpha = 0.4) +
  coord_flip() +
  theme(legend.position = "none") 
```
```{r, eval = F}
ggplot(se, aes(x = park_name, y = visitors)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(se, aes(x = year, y = visitors, color = park_name)) +
   geom_line() #geom_line() is suitable for time series
```
```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) + 
  geom_point() +
  geom_line(col = 'blue ') +
  geom_smooth(se = F, col = 'red ') + #se is shadow
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()
```
```{r}
ggplot(data = visit_16, aes(x = state)) + 
  geom_bar() #y-axis displays counts
```
```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) + #fill is inner color, col is line color
  geom_bar(stat = "identity")
```
```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) + 
  geom_bar(stat = "identity", position = "dodge") #compare with the last picture, use position = "dodge", stack together or seperate
```
```{r}
my_plot <- ggplot(data = mass) + 
      geom_bar(aes(x = type, fill = park_name, col = 'black')) +
  labs(x = "", y = "")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7))
my_plot
#ggsave("name_of_file.png", my_plot, width = 15, height = 10) #use ggsave() to save the plot
```
```{r}
ggplot(iris, aes(Petal.Length, Petal.Width, 
                   color = Species, shape = Species)) + 
  geom_point(size = 3)
```